# -*- coding: utf-8 -*-
"""Workforce Analytics Review - 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgkI0XiXO1U4EPsKSMTPaAlA2VUMsBX9
"""

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("cleaned_ds.csv")
df.head()

"""EDA"""

sns.boxplot(
    x='Attrition',
    y='Salary',
    data=df
)

sns.boxplot(
    x='Attrition',
    y='Experience',
    data=df
)

sns.scatterplot(
    x='Salary',
    y='Performance',
    data=df
)

df.corr(numeric_only=True)