# -*- coding: utf-8 -*-
"""Workforce Analytics Review - 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LU_38LjqQebReY5VxqoSZsWHP0BOsPK
"""

import pandas as pd
import numpy as np

df = pd.read_csv("DS.csv")
df.head()

df.info()

df.isnull().sum()

df['City'].fillna('Unknown', inplace=True)
df['WorkMode'].fillna('Hybrid', inplace=True)

df['Salary'].fillna(df['Salary'].mean(), inplace = True)
df['Age'].fillna(df['Age'].median(), inplace = True)

df['Experience'].fillna(df['Experience'].mode()[0], inplace=True)

df['Education'].unique()

from sklearn.preprocessing import LabelEncoder

education_data = ['B.Sc', 'MBA', 'M.Tech', 'BCA', 'M.Sc', 'B.Com', 'B.Tech', 'MCA']
temp = pd.DataFrame({'Education': education_data})

valid_mask = temp['Education'].notnull()
valid_data = temp.loc[valid_mask, 'Education']

le = LabelEncoder()
encoded_values = le.fit_transform(valid_data)
average_encoded_value = int(round(encoded_values.mean()))
average_label = le.inverse_transform([average_encoded_value])[0]
df['Education'] = df['Education'].fillna(average_label)

from sklearn.preprocessing import LabelEncoder

education_data = ['B.Sc', 'MBA', 'M.Tech', 'BCA', 'M.Sc', 'B.Com', 'B.Tech', 'MCA']
temp_ed = pd.DataFrame({'Education': education_data})

valid_mask = temp_ed['Education'].notnull()
valid_data = temp_ed.loc[valid_mask, 'Education']

le = LabelEncoder()
encoded_values = le.fit_transform(valid_data)
average_encoded_value = int(round(encoded_values.mean()))
average_label = le.inverse_transform([average_encoded_value])[0]
df['Education'] = df['Education'].fillna(average_label)

from sklearn.preprocessing import LabelEncoder

education_data = ['B.Sc', 'MBA', 'M.Tech', 'BCA', 'M.Sc', 'B.Com', 'B.Tech', 'MCA']
temp_pf = pd.DataFrame({'Education': education_data})

valid_mask = temp_pf['Education'].notnull()
valid_data = temp_pf.loc[valid_mask, 'Education']

le = LabelEncoder()
encoded_values = le.fit_transform(valid_data)
average_encoded_value = int(round(encoded_values.mean()))
average_label = le.inverse_transform([average_encoded_value])[0]
df['Performance'] = df['Performance'].fillna(average_label)

df.isnull().sum()

df.duplicated().sum()

df.dtypes

from google.colab import files

df.to_csv('cleaned_ds.csv', index=False)
files.download('cleaned_ds.csv')